/**
 * Centralized Artificial Satellites & Spacecraft Dataset for COSMOS (Segment 4)
 * Curated collection of Space Age Pioneers, ISRO Missions, Space Telescopes, Deep Space Probes & Constellations.
 */

export const ARTIFICIAL_SATELLITES_DATA = [
  // --- SPACE AGE PIONEERS (1957–1970) ---
  {
    id: 'sputnik-1',
    name: 'Sputnik 1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1957,
    countryAgency: 'USSR',
    missionType: 'Technology Demonstration / Science',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'pioneer',
    color: 0xd1d5db,
    orbitalDistance: 8.5,
    orbitSpeed: 1.4,
    rotationSpeed: 0.02,
    diameter: '58 cm sphere',
    orbitalPeriod: '96.2 minutes',
    status: 'Completed Mission (Re-entered 1958)',
    description: 'First artificial satellite in human history; launched by the USSR on October 4, 1957, triggering the Space Age.',
    significance: 'Offered the first space-based radio telemetry and opened human space exploration.'
  },
  {
    id: 'sputnik-2',
    name: 'Sputnik 2',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1957,
    countryAgency: 'USSR',
    missionType: 'Biological Spaceflight',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'pioneer',
    color: 0xa1a1aa,
    orbitalDistance: 9.2,
    orbitSpeed: 1.3,
    rotationSpeed: 0.015,
    diameter: '4 meters capsule',
    orbitalPeriod: '103.7 minutes',
    status: 'Completed Mission',
    description: 'Second spacecraft launched into Earth orbit; carried Laika the dog, the first living creature in orbit.',
    significance: 'Pioneered biological spaceflight data for human space travel.'
  },
  {
    id: 'explorer-1',
    name: 'Explorer 1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1958,
    countryAgency: 'USA / ABMA / JPL',
    missionType: 'Cosmic Ray Detection',
    orbitType: 'Medium Earth Orbit',
    visualTemplate: 'pioneer',
    color: 0x38bdf8,
    orbitalDistance: 10.0,
    orbitSpeed: 1.2,
    rotationSpeed: 0.03,
    diameter: '2.03 m cylinder',
    orbitalPeriod: '114.8 minutes',
    status: 'Completed Mission (Re-entered 1970)',
    description: 'The first satellite launched by the United States. Designed by James Van Allen and built by JPL.',
    significance: 'Discovered the Van Allen radiation belts surrounding Earth.'
  },
  {
    id: 'vanguard-1',
    name: 'Vanguard 1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1958,
    countryAgency: 'USA / US Navy',
    missionType: 'Solar Power Test & Geodesy',
    orbitType: 'Medium Earth Orbit',
    visualTemplate: 'pioneer',
    color: 0xfbbf24,
    orbitalDistance: 11.2,
    orbitSpeed: 1.1,
    rotationSpeed: 0.02,
    diameter: '16.5 cm sphere',
    orbitalPeriod: '134.2 minutes',
    status: 'Inactive (Oldest human object still in orbit)',
    description: 'World\'s first solar-powered satellite. Though silent since 1964, it remains the oldest artificial object orbiting Earth.',
    significance: 'Proved the feasibility of solar photovoltaic cells in space.'
  },
  {
    id: 'tiros-1',
    name: 'TIROS-1',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1960,
    countryAgency: 'USA / NASA / NOAA',
    missionType: 'Meteorology & Earth Imaging',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'radar',
    color: 0x60a5fa,
    orbitalDistance: 12.5,
    orbitSpeed: 1.05,
    rotationSpeed: 0.01,
    diameter: '1.1 m cylinder',
    orbitalPeriod: '99.2 minutes',
    status: 'Completed Mission',
    description: 'World\'s first operational television infrared weather satellite.',
    significance: 'Demonstrated the capability of satellites to track global weather patterns and storm systems.'
  },
  {
    id: 'telstar-1',
    name: 'Telstar 1',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1962,
    countryAgency: 'USA / AT&T / Bell Labs',
    missionType: 'Telecommunications',
    orbitType: 'Elliptical Earth Orbit',
    visualTemplate: 'telecom',
    color: 0x38bdf8,
    orbitalDistance: 13.8,
    orbitSpeed: 0.95,
    rotationSpeed: 0.015,
    diameter: '88 cm sphere',
    orbitalPeriod: '2.5 hours',
    status: 'Completed Mission',
    description: 'First active direct-relay communications satellite.',
    significance: 'Transmitted the world\'s first live transatlantic television pictures, telephone calls, and fax images.'
  },

  // --- INDIAN ISRO HISTORIC & MODERN MISSIONS ---
  {
    id: 'aryabhata',
    name: 'Aryabhata',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1975,
    countryAgency: 'India (ISRO)',
    missionType: 'X-Ray Astronomy & Aeronomy',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'pioneer',
    color: 0xf59e0b,
    orbitalDistance: 15.0,
    orbitSpeed: 0.9,
    rotationSpeed: 0.02,
    diameter: '1.4 m 26-sided polyhedron',
    orbitalPeriod: '96.3 minutes',
    status: 'Completed Mission (Re-entered 1992)',
    description: 'India\'s historic first satellite; named after the famed 5th-century Indian astronomer and launched on April 19, 1975.',
    significance: 'Established India as a spacefaring nation and founded ISRO\'s satellite construction capabilities.'
  },
  {
    id: 'bhaskara-1',
    name: 'Bhaskara-I',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1979,
    countryAgency: 'India (ISRO)',
    missionType: 'Earth Remote Sensing & Hydrology',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'radar',
    color: 0x10b981,
    orbitalDistance: 16.2,
    orbitSpeed: 0.85,
    rotationSpeed: 0.01,
    diameter: '1.4 m polyhedral bus',
    orbitalPeriod: '95.2 minutes',
    status: 'Completed Mission',
    description: 'India\'s first experimental remote sensing satellite, carrying TV cameras and microwave radiometers.',
    significance: 'Pioneered Indian satellite-based forestry, hydrology, and land resource management.'
  },
  {
    id: 'rohini-rs1',
    name: 'Rohini RS-1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1980,
    countryAgency: 'India (ISRO)',
    missionType: 'Launch Vehicle Test',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'pioneer',
    color: 0xef4444,
    orbitalDistance: 17.5,
    orbitSpeed: 0.8,
    rotationSpeed: 0.015,
    diameter: '35 kg compact satellite',
    orbitalPeriod: '97.0 minutes',
    status: 'Completed Mission',
    description: 'First satellite successfully placed into orbit using India\'s indigenous launch vehicle (SLV-3).',
    significance: 'Proved ISRO\'s indigenous orbital launch vehicle capability.'
  },
  {
    id: 'apple',
    name: 'APPLE',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1981,
    countryAgency: 'India (ISRO)',
    missionType: 'Experimental Communications',
    orbitType: 'Geostationary Orbit (GEO)',
    visualTemplate: 'telecom',
    color: 0xfbbf24,
    orbitalDistance: 24.0,
    orbitSpeed: 0.35,
    rotationSpeed: 0.005,
    axialTilt: 0.0,
    diameter: '1.2 m cylindrical bus',
    orbitalPeriod: '24 hours',
    status: 'Completed Mission',
    description: 'Ariane Passenger Payload Experiment (APPLE) was India\'s first 3-axis stabilized geostationary communications satellite.',
    significance: 'Laid the technological bedrock for India\'s national INSAT communication network.'
  },
  {
    id: 'insat-1b',
    name: 'INSAT-1B',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1983,
    countryAgency: 'India (ISRO)',
    missionType: 'Telecom & Meteorology',
    orbitType: 'Geostationary Orbit (GEO)',
    visualTemplate: 'telecom',
    color: 0x38bdf8,
    orbitalDistance: 26.0,
    orbitSpeed: 0.32,
    rotationSpeed: 0.004,
    diameter: '2.1 m bus + 19 m solar array',
    orbitalPeriod: '24 hours',
    status: 'Completed Mission',
    description: 'Multipurpose geostationary satellite that revolutionized Indian national television broadcasting, telephone networks, and severe weather warning systems.',
    significance: 'Catalyzed modern mass telecommunications across all regions of India.'
  },
  {
    id: 'irs-1a',
    name: 'IRS-1A',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1988,
    countryAgency: 'India (ISRO)',
    missionType: 'Civilian Remote Sensing',
    orbitType: 'Sun-Synchronous Orbit (SSO)',
    visualTemplate: 'radar',
    color: 0x34d399,
    orbitalDistance: 18.8,
    orbitSpeed: 0.75,
    rotationSpeed: 0.008,
    diameter: '1.6 m box + solar panels',
    orbitalPeriod: '103 minutes',
    status: 'Completed Mission',
    description: 'India\'s first operational Earth observation satellite, equipped with LISS-I and LISS-II push-broom sensors.',
    significance: 'Established India\'s world-leading civilian remote sensing program.'
  },
  {
    id: 'chandrayaan-1',
    name: 'Chandrayaan-1',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'moon',
    launchYear: 2008,
    countryAgency: 'India (ISRO)',
    missionType: 'Lunar Orbital Exploration',
    orbitType: 'Polar Lunar Orbit',
    visualTemplate: 'probe',
    color: 0xf59e0b,
    orbitalDistance: 3.2,
    orbitSpeed: 1.1,
    rotationSpeed: 0.01,
    diameter: '1.5 m cubical bus',
    orbitalPeriod: '2 hours',
    status: 'Completed Mission',
    description: 'India\'s maiden interplanetary lunar probe launched aboard PSLV-C11 on October 22, 2008.',
    significance: 'Made the landmark scientific discovery of water molecules (H₂O/OH) on the Moon\'s surface using M3.'
  },
  {
    id: 'mangalyaan',
    name: 'Mangalyaan (MOM)',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'mars',
    launchYear: 2013,
    countryAgency: 'India (ISRO)',
    missionType: 'Mars Interplanetary Exploration',
    orbitType: 'Elliptical Mars Orbit',
    visualTemplate: 'probe',
    color: 0xef4444,
    orbitalDistance: 6.8,
    orbitSpeed: 0.9,
    rotationSpeed: 0.01,
    diameter: '1.5 m bus + high-gain dish',
    orbitalPeriod: '72.9 hours',
    status: 'Completed Mission (Operated 8 Years)',
    description: 'Mars Orbiter Mission (MOM) made India the first Asian nation to reach Mars orbit, achieving success on its maiden attempt.',
    significance: 'Globally celebrated for extreme cost-efficiency ($74M) and 8 years of continuous Martian observations.'
  },
  {
    id: 'astrosat',
    name: 'AstroSat',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 2015,
    countryAgency: 'India (ISRO)',
    missionType: 'Multi-Wavelength Space Observatory',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'telescope',
    color: 0x818cf8,
    orbitalDistance: 19.8,
    orbitSpeed: 0.7,
    rotationSpeed: 0.008,
    diameter: '1.8 m spacecraft bus',
    orbitalPeriod: '98 minutes',
    status: 'Active',
    description: 'India\'s first dedicated astronomy space observatory, simultaneously studying objects in UV, optical, soft X-ray, and hard X-ray bands.',
    significance: 'Discovered extreme UV emissions from distant galaxies and cosmic black hole binary systems.'
  },
  {
    id: 'cartosat-3',
    name: 'Cartosat-3',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 2019,
    countryAgency: 'India (ISRO)',
    missionType: 'High-Resolution Earth Observation',
    orbitType: 'Sun-Synchronous Orbit (SSO)',
    visualTemplate: 'radar',
    color: 0x38bdf8,
    orbitalDistance: 21.0,
    orbitSpeed: 0.65,
    rotationSpeed: 0.008,
    diameter: '2.0 m optical bus',
    orbitalPeriod: '94.8 minutes',
    status: 'Active',
    description: '3rd generation high-resolution optical imager featuring ground sampling distance of 0.28 meters.',
    significance: 'Provides sub-meter urban mapping and infrastructure intelligence.'
  },
  {
    id: 'chandrayaan-3',
    name: 'Chandrayaan-3 Propulsion',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'moon',
    launchYear: 2023,
    countryAgency: 'India (ISRO)',
    missionType: 'Lunar Transport & SHAPE Payload',
    orbitType: 'Lunar Orbit',
    visualTemplate: 'probe',
    color: 0xf59e0b,
    orbitalDistance: 4.5,
    orbitSpeed: 0.95,
    rotationSpeed: 0.01,
    diameter: '2.0 m box bus',
    orbitalPeriod: '2.1 hours',
    status: 'Active (Conducting SHAPE observations)',
    description: 'The propulsion module that carried India\'s historic Vikram lander and Pragyan rover to the Moon\'s south polar touchdown.',
    significance: 'Made India the 4th nation to soft-land on the Moon and the first at the Lunar South Pole.'
  },
  {
    id: 'aditya-l1',
    name: 'Aditya-L1',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2023,
    countryAgency: 'India (ISRO)',
    missionType: 'Solar Physics & Space Weather',
    orbitType: 'Sun-Earth L1 Halo Orbit',
    visualTemplate: 'probe',
    color: 0xfbbf24,
    orbitalDistance: 32.0,
    orbitSpeed: 0.5,
    rotationSpeed: 0.008,
    diameter: '1.5 m solar observatory',
    orbitalPeriod: '178 days halo orbit',
    status: 'Active',
    description: 'India\'s inaugural solar space observatory, positioned at Lagrange Point L1 (~1.5M km from Earth) to observe the Sun\'s corona continuously.',
    significance: 'Monitors solar flares, coronal mass ejections (CMEs), and geomagnetic solar wind storms uninterrupted by eclipses.'
  },
  {
    id: 'nisar',
    name: 'NISAR',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 2025,
    countryAgency: 'NASA / ISRO',
    missionType: 'Dual-Frequency SAR Radar',
    orbitType: 'Sun-Synchronous Orbit (SSO)',
    visualTemplate: 'radar',
    color: 0x34d399,
    orbitalDistance: 22.5,
    orbitSpeed: 0.6,
    rotationSpeed: 0.006,
    diameter: '12 m deployable reflector dish antenna',
    orbitalPeriod: '98.5 minutes',
    status: 'Active / Launched',
    description: 'NASA-ISRO Synthetic Aperture Radar (NISAR) carries L-band and S-band dual-frequency radar to map Earth\'s land ecosystems, glaciers, and seismic crustal shifts globally every 12 days.',
    significance: 'Largest joint earth-science satellite collaboration between NASA and ISRO.'
  },

  // --- GREAT SPACE TELESCOPES & DEEP SPACE OBSERVATORIES ---
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1990,
    countryAgency: 'NASA / ESA',
    missionType: 'Optical & UV Astronomy',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'telescope',
    color: 0x38bdf8,
    orbitalDistance: 23.5,
    orbitSpeed: 0.58,
    rotationSpeed: 0.005,
    diameter: '13.2 m cylinder + 2.4 m mirror',
    orbitalPeriod: '95.4 minutes',
    status: 'Active (35+ Years in Service)',
    description: 'The iconic optical space observatory deployed by Space Shuttle Discovery in 1990, capturing ultra-deep views of early galaxies.',
    significance: 'Precisely measured the expansion rate of the universe (Hubble Constant) and confirmed dark energy.'
  },
  {
    id: 'james-webb',
    name: 'James Webb Space Telescope (JWST)',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2021,
    countryAgency: 'NASA / ESA / CSA',
    missionType: 'Infrared Astronomy & Exoplanets',
    orbitType: 'Sun-Earth L2 Halo Orbit',
    visualTemplate: 'telescope',
    color: 0xf59e0b,
    orbitalDistance: 40.0,
    orbitSpeed: 0.4,
    rotationSpeed: 0.004,
    diameter: '6.5 m beryllium gold mirror + 22 m sunshield',
    orbitalPeriod: '6 months L2 orbit',
    status: 'Active',
    description: 'The premier infrared observatory in human history, featuring a 6.5-meter gold-plated primary mirror and tennis-court-sized sunshield operating at Lagrange Point 2.',
    significance: 'Observes the first galaxies formed after the Big Bang and analyzes exoplanetary atmospheres for biosignatures.'
  },
  {
    id: 'kepler',
    name: 'Kepler Space Telescope',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2009,
    countryAgency: 'NASA',
    missionType: 'Exoplanet Transit Photometry',
    orbitType: 'Heliocentric Orbit',
    visualTemplate: 'telescope',
    color: 0xa855f7,
    orbitalDistance: 36.0,
    orbitSpeed: 0.45,
    rotationSpeed: 0.005,
    diameter: '4.7 m space telescope',
    orbitalPeriod: '372 days',
    status: 'Completed Mission',
    description: 'NASA\'s specialized planet-hunting space telescope that continuously monitored over 150,000 stars.',
    significance: 'Discovered over 2,600 verified exoplanets, proving planets outnumber stars in our galaxy.'
  },
  {
    id: 'spitzer',
    name: 'Spitzer Space Telescope',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2003,
    countryAgency: 'NASA',
    missionType: 'Infrared Astronomy',
    orbitType: 'Earth-Trailing Heliocentric',
    visualTemplate: 'telescope',
    color: 0xec4899,
    orbitalDistance: 34.0,
    orbitSpeed: 0.48,
    rotationSpeed: 0.005,
    diameter: '4.4 m telescope assembly',
    orbitalPeriod: '370 days',
    status: 'Completed Mission',
    description: 'NASA Great Observatory designed to study the cool universe in infrared wavelengths, piercing dust clouds.',
    significance: 'Discovered the 7 Earth-sized TRAPPIST-1 exoplanet system.'
  },

  // --- MODERN CONSTELLATIONS & EXPLORERS ---
  {
    id: 'starlink',
    name: 'Starlink Constellation Representative',
    category: 'artificial',
    layer: 'constellations',
    parentBodyId: 'earth',
    launchYear: 2019,
    countryAgency: 'SpaceX (USA)',
    missionType: 'Global Satellite Internet Broadband',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'telecom',
    color: 0x38bdf8,
    orbitalDistance: 8.0,
    orbitSpeed: 1.5,
    rotationSpeed: 0.02,
    diameter: '3.2 m flat panel + solar array',
    orbitalPeriod: '95 minutes',
    status: 'Active (6,000+ Satellites Operating)',
    description: 'Representative satellite from SpaceX\'s LEO megaconstellation delivering high-speed low-latency broadband internet worldwide.',
    significance: 'World\'s largest commercial satellite constellation.'
  },
  {
    id: 'dart',
    name: 'DART Spacecraft',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2021,
    countryAgency: 'NASA / JHUAPL',
    missionType: 'Kinetic Asteroid Deflection',
    orbitType: 'Heliocentric Asteroid Intercept',
    visualTemplate: 'probe',
    color: 0xf43f5e,
    orbitalDistance: 38.0,
    orbitSpeed: 0.42,
    rotationSpeed: 0.01,
    diameter: '1.3 m bus + 8.5 m solar arrays',
    orbitalPeriod: 'Interplanetary',
    status: 'Completed Mission (Impacted Dimorphos 2022)',
    description: 'Double Asteroid Redirection Test (DART) was the world\'s first planetary defense technology demonstration mission.',
    significance: 'Intentionally impacted binary asteroid Dimorphos, successfully shortening its orbit by 33 minutes.'
  }
];
