/**
 * Centralized Configuration & Metadata for Solar System Objects
 * Expanded for Segment 3 with Scientific Data.
 */

export const SUN_CONFIG = {
  id: 'sun',
  name: 'Sun',
  type: 'Yellow Dwarf Star',
  radius: 14,
  realRadius: 218.0,
  color: 0xffaa00,
  emissive: 0xffaa00,
  emissiveIntensity: 1.2,
  glowColor: 0xff6600,
  description: 'The star at the center of the Solar System. It is a nearly perfect ball of hot plasma, heating the planets and driving Earth\'s weather and climate.',
  positionFromSun: 'Center of Solar System',
  diameter: '1,392,700 km (109x Earth)',
  distanceFromSun: '0 km',
  orbitalPeriod: 'N/A (Galactic Orbit ~230M yrs)',
  rotationPeriod: '27 days',
  moonsCount: '8 Planets, 200+ Moons',
  mass: '1.989 × 10³⁰ kg (333,000x Earth)',
  surfaceTemp: '5,500 °C (Core: 15 Million °C)',
  atmosphere: '73% Hydrogen, 25% Helium',
  gravity: '274.0 m/s² (28x Earth)'
};

export const PLANETS_DATA = [
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'Terrestrial Planet',
    radius: 1.2,
    realRadius: 0.76,
    distance: 28,
    realDistance: 39,
    orbitSpeed: 0.8,
    rotationSpeed: 0.005,
    axialTilt: 0.03,
    color: 0xa8a5a0,
    textureType: 'mercury',
    orbitColor: 0x4a5568,
    description: 'The smallest planet in the Solar System and closest to the Sun. Its surface is heavily cratered and experiences extreme temperature fluctuations.',
    positionFromSun: '1st Planet from Sun',
    diameter: '4,879 km (0.38x Earth)',
    distanceFromSun: '57.9 million km (0.39 AU)',
    orbitalPeriod: '88 days',
    rotationPeriod: '59 days',
    moonsCount: '0',
    mass: '3.301 × 10²³ kg (0.055x Earth)',
    surfaceTemp: '-180 °C to 430 °C',
    atmosphere: 'Trace Sodium, Helium, Oxygen',
    gravity: '3.7 m/s² (0.38x Earth)'
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'Terrestrial Planet',
    radius: 2.2,
    realRadius: 1.90,
    distance: 42,
    realDistance: 72,
    orbitSpeed: 0.6,
    rotationSpeed: -0.003,
    axialTilt: 177.3,
    color: 0xe3bb76,
    textureType: 'venus',
    orbitColor: 0x5a6578,
    description: 'Spinning in the opposite direction to most planets, Venus has a runaway greenhouse effect making it the hottest planet in the Solar System.',
    positionFromSun: '2nd Planet from Sun',
    diameter: '12,104 km (0.95x Earth)',
    distanceFromSun: '108.2 million km (0.72 AU)',
    orbitalPeriod: '225 days',
    rotationPeriod: '243 days (Retrograde)',
    moonsCount: '0',
    mass: '4.867 × 10²⁴ kg (0.815x Earth)',
    surfaceTemp: '465 °C (Mean)',
    atmosphere: '96.5% Carbon Dioxide, 3.5% Nitrogen',
    gravity: '8.87 m/s² (0.90x Earth)'
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'Terrestrial Planet',
    radius: 2.5,
    realRadius: 2.00,
    distance: 60,
    realDistance: 100,
    orbitSpeed: 0.45,
    rotationSpeed: 0.01,
    axialTilt: 23.44,
    color: 0x2b82c5,
    textureType: 'earth',
    hasAtmosphere: true,
    atmosphereColor: 0x38bdf8,
    orbitColor: 0x3b82f6,
    description: 'The third planet from the Sun and the only astronomical object known to harbor life. Liquid water oceans cover 71% of its surface.',
    positionFromSun: '3rd Planet from Sun',
    diameter: '12,742 km (1.00x Earth)',
    distanceFromSun: '149.6 million km (1.00 AU)',
    orbitalPeriod: '365.25 days',
    rotationPeriod: '24 hours',
    moonsCount: '1 (The Moon)',
    mass: '5.972 × 10²⁴ kg',
    surfaceTemp: '15 °C (Mean)',
    atmosphere: '78% Nitrogen, 21% Oxygen, 1% Argon',
    gravity: '9.81 m/s² (1.00x Earth)'
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'Terrestrial Planet',
    radius: 1.6,
    realRadius: 1.06,
    distance: 78,
    realDistance: 152,
    orbitSpeed: 0.35,
    rotationSpeed: 0.009,
    axialTilt: 25.19,
    color: 0xc1440e,
    textureType: 'mars',
    orbitColor: 0x64748b,
    description: 'Often called the "Red Planet" due to iron oxide rust on its surface. Mars features Olympus Mons, the largest volcano in the Solar System.',
    positionFromSun: '4th Planet from Sun',
    diameter: '6,779 km (0.53x Earth)',
    distanceFromSun: '227.9 million km (1.52 AU)',
    orbitalPeriod: '687 days',
    rotationPeriod: '24.6 hours',
    moonsCount: '2 (Phobos & Deimos)',
    mass: '6.417 × 10²³ kg (0.107x Earth)',
    surfaceTemp: '-63 °C (Mean)',
    atmosphere: '95% Carbon Dioxide, 2.6% Nitrogen',
    gravity: '3.72 m/s² (0.38x Earth)'
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'Gas Giant',
    radius: 7.2,
    realRadius: 22.42,
    distance: 108,
    realDistance: 520,
    orbitSpeed: 0.22,
    rotationSpeed: 0.025,
    axialTilt: 3.13,
    color: 0xb07f35,
    textureType: 'jupiter',
    orbitColor: 0x475569,
    description: 'The largest planet in the Solar System. Jupiter is a gas giant with iconic atmospheric bands and the Great Red Spot, a storm larger than Earth.',
    positionFromSun: '5th Planet from Sun',
    diameter: '139,820 km (11.21x Earth)',
    distanceFromSun: '778.5 million km (5.20 AU)',
    orbitalPeriod: '11.86 years',
    rotationPeriod: '9.9 hours',
    moonsCount: '95 known moons',
    mass: '1.898 × 10²⁷ kg (318x Earth)',
    surfaceTemp: '-110 °C (Cloud tops)',
    atmosphere: '90% Hydrogen, 10% Helium',
    gravity: '24.79 m/s² (2.53x Earth)'
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'Gas Giant',
    radius: 5.8,
    realRadius: 18.90,
    distance: 148,
    realDistance: 954,
    orbitSpeed: 0.15,
    rotationSpeed: 0.022,
    axialTilt: 26.73,
    color: 0xe2bf7d,
    textureType: 'saturn',
    hasRings: true,
    ringConfig: {
      innerRadius: 7.5,
      outerRadius: 13.5,
      realInnerRadius: 23.0,
      realOuterRadius: 42.0,
      color: 0xd4b886,
      textureType: 'saturnRings'
    },
    orbitColor: 0x475569,
    description: 'Renowned for its spectacular, complex ring system composed of billions of chunks of ice and rock particles.',
    positionFromSun: '6th Planet from Sun',
    diameter: '116,460 km (9.45x Earth)',
    distanceFromSun: '1.43 billion km (9.54 AU)',
    orbitalPeriod: '29.45 years',
    rotationPeriod: '10.7 hours',
    moonsCount: '146 known moons',
    mass: '5.683 × 10²⁶ kg (95x Earth)',
    surfaceTemp: '-140 °C (Cloud tops)',
    atmosphere: '96% Hydrogen, 3% Helium',
    gravity: '10.44 m/s² (1.06x Earth)'
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'Ice Giant',
    radius: 3.8,
    realRadius: 8.02,
    distance: 185,
    realDistance: 1919,
    orbitSpeed: 0.1,
    rotationSpeed: -0.015,
    axialTilt: 97.77,
    color: 0x4b70dd,
    textureType: 'uranus',
    hasRings: true,
    ringConfig: {
      innerRadius: 4.8,
      outerRadius: 6.8,
      realInnerRadius: 10.0,
      realOuterRadius: 14.0,
      color: 0x76a0d0,
      textureType: 'uranusRings'
    },
    orbitColor: 0x334155,
    description: 'An ice giant with a unique sideways rotation, tilted nearly 98 degrees on its axis. It has a pale cyan atmosphere rich in methane ice.',
    positionFromSun: '7th Planet from Sun',
    diameter: '50,724 km (4.01x Earth)',
    distanceFromSun: '2.87 billion km (19.19 AU)',
    orbitalPeriod: '84 years',
    rotationPeriod: '17.2 hours',
    moonsCount: '28 known moons',
    mass: '8.681 × 10²⁵ kg (14.5x Earth)',
    surfaceTemp: '-195 °C (Mean)',
    atmosphere: '83% Hydrogen, 15% Helium, 2% Methane',
    gravity: '8.69 m/s² (0.89x Earth)'
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'Ice Giant',
    radius: 3.6,
    realRadius: 7.76,
    distance: 220,
    realDistance: 3007,
    orbitSpeed: 0.07,
    rotationSpeed: 0.016,
    axialTilt: 28.32,
    color: 0x274687,
    textureType: 'neptune',
    orbitColor: 0x334155,
    description: 'The outermost major planet in the Solar System. Neptune is a deep azure blue ice giant with supersonic winds reaching over 2,000 km/h.',
    positionFromSun: '8th Planet from Sun',
    diameter: '49,244 km (3.88x Earth)',
    distanceFromSun: '4.50 billion km (30.07 AU)',
    orbitalPeriod: '164.8 years',
    rotationPeriod: '16.1 hours',
    moonsCount: '16 known moons',
    mass: '1.024 × 10²⁶ kg (17x Earth)',
    surfaceTemp: '-200 °C (Mean)',
    atmosphere: '80% Hydrogen, 19% Helium, 1% Methane',
    gravity: '11.15 m/s² (1.14x Earth)'
  }
];
