/**
 * Centralized Satellite & Moon Data Configuration for COSMOS (Segment 4)
 * Configures 16 Major Natural Satellites across Earth, Mars, Jupiter, Saturn, Uranus, Neptune.
 */

export const SATELLITES_DATA = [
  // --- EARTH ---
  {
    id: 'moon',
    name: 'The Moon',
    parentPlanetId: 'earth',
    type: 'Natural Satellite',
    radius: 0.8,
    distanceFromParent: 6.5,
    orbitSpeed: 0.8,
    rotationSpeed: 0.008,
    axialTilt: 6.68,
    color: 0xc8c8c8,
    textureType: 'moon',
    description: 'Earth\'s only natural satellite. The Moon is in synchronous rotation with Earth, always showing the same side to us.',
    diameter: '3,474 km (0.27x Earth)',
    distanceFromPlanet: '384,400 km',
    orbitalPeriod: '27.3 days',
    rotationPeriod: '27.3 days (Synchronous)',
    mass: '7.342 × 10²² kg',
    surfaceTemp: '-130 °C to 120 °C',
    composition: 'Silicate Rock, Anorthosite'
  },

  // --- MARS ---
  {
    id: 'phobos',
    name: 'Phobos',
    parentPlanetId: 'mars',
    type: 'Natural Satellite',
    radius: 0.45,
    distanceFromParent: 3.6,
    orbitSpeed: 1.6,
    rotationSpeed: 0.01,
    axialTilt: 1.0,
    color: 0x8a7f78,
    textureType: 'phobos',
    description: 'The larger and innermost of the two Martian moons. Phobos orbits closer to its primary than any other moon in the Solar System.',
    diameter: '22.5 km',
    distanceFromPlanet: '9,376 km',
    orbitalPeriod: '7.6 hours',
    rotationPeriod: '7.6 hours (Synchronous)',
    mass: '1.065 × 10¹⁶ kg',
    surfaceTemp: '-40 °C (Mean)',
    composition: 'Carbonaceous Chondrite'
  },
  {
    id: 'deimos',
    name: 'Deimos',
    parentPlanetId: 'mars',
    type: 'Natural Satellite',
    radius: 0.35,
    distanceFromParent: 5.2,
    orbitSpeed: 1.1,
    rotationSpeed: 0.008,
    axialTilt: 1.8,
    color: 0x9a8f88,
    textureType: 'phobos',
    description: 'The smaller and outermost of Mars\'s two moons. Deimos has a smooth surface covered by a thick layer of regolith dust.',
    diameter: '12.4 km',
    distanceFromPlanet: '23,463 km',
    orbitalPeriod: '30.3 hours',
    rotationPeriod: '30.3 hours',
    mass: '1.471 × 10¹⁵ kg',
    surfaceTemp: '-40 °C (Mean)',
    composition: 'Rich in Carbonaceous Material'
  },

  // --- JUPITER (GALILEAN MOONS) ---
  {
    id: 'io',
    name: 'Io',
    parentPlanetId: 'jupiter',
    type: 'Galilean Satellite',
    radius: 1.05,
    distanceFromParent: 12.0,
    orbitSpeed: 1.2,
    rotationSpeed: 0.01,
    axialTilt: 0.0,
    color: 0xf59e0b,
    textureType: 'io',
    description: 'The most volcanically active body in the Solar System, with hundreds of active volcanoes erupting plumes of sulfur and sulfur dioxide.',
    diameter: '3,643 km',
    distanceFromPlanet: '421,700 km',
    orbitalPeriod: '1.77 days',
    rotationPeriod: '1.77 days (Synchronous)',
    mass: '8.931 × 10²² kg',
    surfaceTemp: '-130 °C (Lava: 1,200 °C)',
    atmosphere: 'Sulfur Dioxide'
  },
  {
    id: 'europa',
    name: 'Europa',
    parentPlanetId: 'jupiter',
    type: 'Galilean Satellite',
    radius: 0.95,
    distanceFromParent: 16.5,
    orbitSpeed: 0.9,
    rotationSpeed: 0.009,
    axialTilt: 0.1,
    color: 0x38bdf8,
    textureType: 'europa',
    description: 'Features a smooth, fractured ice shell covering a liquid water ocean containing more water than all of Earth\'s oceans combined.',
    diameter: '3,121 km',
    distanceFromPlanet: '670,900 km',
    orbitalPeriod: '3.55 days',
    rotationPeriod: '3.55 days (Synchronous)',
    mass: '4.800 × 10²² kg',
    surfaceTemp: '-170 °C (Mean)',
    composition: 'Water Ice Crust, Ocean, Iron Core'
  },
  {
    id: 'ganymede',
    name: 'Ganymede',
    parentPlanetId: 'jupiter',
    type: 'Galilean Satellite',
    radius: 1.35,
    distanceFromParent: 22.0,
    orbitSpeed: 0.65,
    rotationSpeed: 0.007,
    axialTilt: 0.2,
    color: 0x94a3b8,
    textureType: 'moon',
    description: 'The largest moon in the Solar System, larger even than the planet Mercury. It is the only moon known to possess its own magnetic field.',
    diameter: '5,268 km (0.41x Earth)',
    distanceFromPlanet: '1,070,400 km',
    orbitalPeriod: '7.15 days',
    rotationPeriod: '7.15 days (Synchronous)',
    mass: '1.481 × 10²³ kg',
    surfaceTemp: '-160 °C (Mean)',
    composition: 'Silicate Rock, Deep Water-Ice Mantle'
  },
  {
    id: 'callisto',
    name: 'Callisto',
    parentPlanetId: 'jupiter',
    type: 'Galilean Satellite',
    radius: 1.25,
    distanceFromParent: 28.5,
    orbitSpeed: 0.45,
    rotationSpeed: 0.005,
    axialTilt: 0.3,
    color: 0x64748b,
    textureType: 'phobos',
    description: 'The most heavily cratered object in the Solar System. Callisto\'s ancient surface has shown little geological activity over the last 4 billion years.',
    diameter: '4,821 km',
    distanceFromPlanet: '1,882,700 km',
    orbitalPeriod: '16.69 days',
    rotationPeriod: '16.69 days',
    mass: '1.076 × 10²³ kg',
    surfaceTemp: '-140 °C (Mean)',
    composition: 'Ice and Rock mixture'
  },

  // --- SATURN ---
  {
    id: 'titan',
    name: 'Titan',
    parentPlanetId: 'saturn',
    type: 'Major Satellite',
    radius: 1.3,
    distanceFromParent: 22.0,
    orbitSpeed: 0.55,
    rotationSpeed: 0.006,
    axialTilt: 0.3,
    color: 0xf59e0b,
    textureType: 'titan',
    description: 'Saturn\'s largest moon and the only moon in the Solar System with a dense nitrogen atmosphere, rivers, and liquid methane lakes.',
    diameter: '5,149 km (0.40x Earth)',
    distanceFromPlanet: '1,221,870 km',
    orbitalPeriod: '15.95 days',
    rotationPeriod: '15.95 days (Synchronous)',
    mass: '1.345 × 10²³ kg',
    surfaceTemp: '-179 °C',
    atmosphere: '98.4% Nitrogen, 1.4% Methane'
  },
  {
    id: 'enceladus',
    name: 'Enceladus',
    parentPlanetId: 'saturn',
    type: 'Major Satellite',
    radius: 0.7,
    distanceFromParent: 16.0,
    orbitSpeed: 0.85,
    rotationSpeed: 0.008,
    axialTilt: 0.0,
    color: 0xe0f2fe,
    textureType: 'enceladus',
    description: 'A bright, snow-white icy moon featuring active cryovolcanic geysers erupting water ice plumes into space from a subsurface ocean.',
    diameter: '504 km',
    distanceFromPlanet: '238,000 km',
    orbitalPeriod: '1.37 days',
    rotationPeriod: '1.37 days',
    mass: '1.080 × 10²⁰ kg',
    surfaceTemp: '-201 °C',
    composition: 'Pure Water Ice Crust'
  },
  {
    id: 'rhea',
    name: 'Rhea',
    parentPlanetId: 'saturn',
    type: 'Major Satellite',
    radius: 0.85,
    distanceFromParent: 27.0,
    orbitSpeed: 0.45,
    rotationSpeed: 0.005,
    axialTilt: 0.1,
    color: 0xc0c5ce,
    textureType: 'moon',
    description: 'Saturn\'s second-largest moon. Rhea is a heavily cratered icy body composed of roughly 75% water ice and 25% rock.',
    diameter: '1,527 km',
    distanceFromPlanet: '527,108 km',
    orbitalPeriod: '4.52 days',
    rotationPeriod: '4.52 days',
    mass: '2.306 × 10²¹ kg',
    surfaceTemp: '-174 °C',
    composition: 'Water Ice, Silicate Rock'
  },
  {
    id: 'iapetus',
    name: 'Iapetus',
    parentPlanetId: 'saturn',
    type: 'Major Satellite',
    radius: 0.8,
    distanceFromParent: 34.0,
    orbitSpeed: 0.3,
    rotationSpeed: 0.004,
    axialTilt: 15.3,
    color: 0x475569,
    textureType: 'phobos',
    description: 'Famous for its two-tone coloration: one hemisphere is dark as coal while the other is bright as snow.',
    diameter: '1,469 km',
    distanceFromPlanet: '3,560,820 km',
    orbitalPeriod: '79.32 days',
    rotationPeriod: '79.32 days',
    mass: '1.805 × 10²¹ kg',
    surfaceTemp: '-180 °C',
    composition: 'Low-density Ice/Rock'
  },

  // --- URANUS ---
  {
    id: 'titania',
    name: 'Titania',
    parentPlanetId: 'uranus',
    type: 'Major Satellite',
    radius: 0.8,
    distanceFromParent: 12.0,
    orbitSpeed: 0.6,
    rotationSpeed: 0.006,
    axialTilt: 0.0,
    color: 0xa1a1aa,
    textureType: 'moon',
    description: 'The largest moon of Uranus. Titania\'s surface is cut by a massive system of canyons and fault scarps.',
    diameter: '1,578 km',
    distanceFromPlanet: '435,910 km',
    orbitalPeriod: '8.71 days',
    rotationPeriod: '8.71 days',
    mass: '3.400 × 10²¹ kg',
    surfaceTemp: '-203 °C',
    composition: 'Water Ice, Organic Compounds'
  },
  {
    id: 'oberon',
    name: 'Oberon',
    parentPlanetId: 'uranus',
    type: 'Major Satellite',
    radius: 0.75,
    distanceFromParent: 15.5,
    orbitSpeed: 0.45,
    rotationSpeed: 0.005,
    axialTilt: 0.0,
    color: 0x71717a,
    textureType: 'phobos',
    description: 'The second-largest moon of Uranus and the outermost of its major moons, covered in numerous large impact craters.',
    diameter: '1,523 km',
    distanceFromPlanet: '583,520 km',
    orbitalPeriod: '13.46 days',
    rotationPeriod: '13.46 days',
    mass: '3.014 × 10²¹ kg',
    surfaceTemp: '-205 °C',
    composition: 'Ice and Rock'
  },
  {
    id: 'ariel',
    name: 'Ariel',
    parentPlanetId: 'uranus',
    type: 'Major Satellite',
    radius: 0.65,
    distanceFromParent: 8.5,
    orbitSpeed: 0.85,
    rotationSpeed: 0.008,
    axialTilt: 0.0,
    color: 0xd4d4d8,
    textureType: 'moon',
    description: 'The brightest and geological youngest of Uranus\'s moons, crisscrossed by expansive valleys and fault canyons.',
    diameter: '1,158 km',
    distanceFromPlanet: '191,020 km',
    orbitalPeriod: '2.52 days',
    rotationPeriod: '2.52 days',
    mass: '1.251 × 10²¹ kg',
    surfaceTemp: '-213 °C',
    composition: 'Water Ice, Carbon Dioxide'
  },

  // --- NEPTUNE ---
  {
    id: 'triton',
    name: 'Triton',
    parentPlanetId: 'neptune',
    type: 'Major Satellite',
    radius: 1.0,
    distanceFromParent: 14.0,
    orbitSpeed: -0.7, // Retrograde orbit!
    rotationSpeed: 0.007,
    axialTilt: 157.0,
    color: 0x34d399,
    textureType: 'triton',
    description: 'Neptune\'s largest moon and the only large moon in the Solar System with a retrograde orbit (orbiting opposite to the planet\'s rotation).',
    diameter: '2,706 km',
    distanceFromPlanet: '354,759 km',
    orbitalPeriod: '5.88 days (Retrograde)',
    rotationPeriod: '5.88 days',
    mass: '2.140 × 10²² kg',
    surfaceTemp: '-235 °C (Coldest body in Solar System)',
    composition: 'Frozen Nitrogen, Water Ice'
  }
];
